namespace: pihole

image:
  repository: ghcr.io/pi-hole/pihole
  tag: "2024.07.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  loadBalancerIP: "192.168.44.207"   # set to "" if you don't want a static IP

env:
  FTLCONF_webserver_port: "80"
  VIRTUAL_HOST: "pi.hole"
  FTLCONF_misc_etc_dnsmasq_d: "true"
  FTLCONF_webserver_api_password: "hunDekuchen"
  FTLCONF_dns_listeningMode: "all"
  FTLCONF_dns_upstreams: "8.8.8.8;8.8.4.4"

persistence:
  enabled: true
  existingClaim: ""        # if set, this claim will be used and no PVC created
  claimName: "pihole-v2-etc"
  storageClassName: "nfs-csi"
  accessModes: ["ReadWriteOnce"]
  size: 5Gi

configmap:
  nameOverride: ""         # leave empty to use fullname
  data:
    02-custom.conf: |-
      addn-hosts=/etc/addn-hosts
    05-pihole-custom-cname.conf: ""
    addn-hosts: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

dnsConfig:
  nameservers:
    - 127.0.0.1
    - 8.8.8.8
