apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-pv-claim-helm
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: localstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
