apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dnsmasq3
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
