apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-etc3
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
