apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-helm
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  storageClassName: localstorage
  capacity:
    storage: 6Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/var/microk8s/pihole-helm/dnsmasq"
