apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: {{ .Values.namespace }}
  labels:
    name: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      securityContext:
{{/*        runAsUser: 1000*/}}
{{/*        runAsGroup: 1000*/}}
        fsGroup: 1000
      containers:
      - name: pihole
        image: "{{ .Values.image }}:{{- .Chart.AppVersion -}}"
        imagePullPolicy: "IfNotPresent"
        envFrom:
        - configMapRef:
            name: pihole-config
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_NICE
              - CHOWN
        volumeMounts:
         - name: pihole-local-etc-volume
           mountPath: '/etc/pihole'
         - name: pihole-local-dnsmasq-volume
           mountPath: '/etc/dnsmasq.d'
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 9.9.9.9
          - 1.1.1.1
        searches:
          - pihole.svc.cluster.local
          - svc.cluster.local
          - cluster.local
          - fritz.box
        options:
          - name: ndots
            value: "2"
      volumes:
      - name: pihole-local-etc-volume
        persistentVolumeClaim:
          claimName: pihole-etc-pv
      - name: pihole-local-dnsmasq-volume
        persistentVolumeClaim:
          claimName: pihole-dnsmasq-pvc
