apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteMany"]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.44.200
    path: /srv/nfs/pvc-af9f51c8-3730-4390-8d55-83c6fefb238f