apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ""         # must be empty to bind static PV
  resources:
    requests:
      storage: 2Gi
  volumeName: pihole-etc-pv