apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-etc-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteMany"]
  storageClassName: ""     # static PV
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.44.200
    path: /srv/nfs/pvc-17ef0d80-a8c5-41e7-a865-8ef9325e07f6