{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  accessModes: {{ toJson .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
