apiVersion: v1
kind: Service
metadata:
  name: pihole-svc-tcp
  namespace: {{ .Values.namespace }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Values.shared_ip }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.shared_ip }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app: pihole
