apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  allocateLoadBalancerNodePorts: true
  {{- if and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  selector:
    app: {{ include "pihole.fullname" . }}
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
    - name: dns
      port: 53
      protocol: TCP
      targetPort: dns
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
