apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: {{ .Values.namespace }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole"
    metallb.universe.tf/loadBalancerIPs: '["192.168.44.205","2001:8e0:2078:c400::205"]'
spec:
  type: LoadBalancer
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: pihole
