apiVersion: v1
kind: Service
metadata:
  name: pihole-svc-udp
  namespace: {{ .Values.namespace }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Values.shared_ip }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.shared_ip }}
  ports:
    - port: 80
      targetPort: 80
      protocol: UDP
      name: http
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
  selector:
    app: pihole
